language: java
  
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew assemble
  - ./gradlew check
  - ./gradlew assembleDist

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $HOME/build/distributions/*.zip
  skip_cleanup: true
  

